eventplanner/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import events.views

urlpatterns = [
    url(r'', include('events.urls')),
    url(r'^login/$', events.views.LoginView.as_view(), name='login'),
    url(r'^logout/$', events.views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
]

events/urls.py
from django.conf.urls import url
from django.views.decorators.http import require_POST

from . import views

app_name = "events"
urlpatterns = [
    url(r'^$', views.EventListView.as_view(), name="home"),
    url(r'^create/$', views.CreateEventView.as_view(), name="create"),
    url(r'^update/(?P<pk>\d+)/$', views.UpdateEventView.as_view(), name="update"),
    url(r'^details/(?P<pk>\d+)/$', views.DetailsEventView.as_view(), name="details"),
    url(r'^guest/$', views.CreateGuestView.as_view(), name="guest"),
    url(r'^rsvp/(?P<slug>\w+)$', views.GuestResponseView.as_view(), name="response"),

    # url(r'^add/$', views.CreateExpenseView.as_view(), name="create"),
]

events/models.py
from django.contrib import auth
from django.db import models
from django.utils.translation import ugettext as _


class Event(models.Model):
    choices = ((1, 'open'), (2, 'cancelled'), (3, 'postponed'), (4, 'closed'))
    title = models.CharField(_('title'), max_length=50)
    start = models.DateTimeField(_('starts at'))
    end = models.DateTimeField(_('ends at'))
    description = models.TextField(_('description'), max_length=3000, null=True, blank=True)
    price = models.PositiveIntegerField(_('price'), null=True, blank=True)
    status = models.IntegerField(_('status'), choices=choices, default=1)

    location = models.CharField(_('location'), max_length=50, null=True, blank=True, default="tel aviv")
    longitude = models.DecimalField(max_digits=16, decimal_places=12, null=True, blank=True)
    latitude = models.DecimalField(max_digits=16, decimal_places=12, null=True, blank=True)

    host = models.ForeignKey(auth.models.User, related_name='events', verbose_name=_('host'))


    def __str__(self):
        return self.title


class Item(models.Model):
    title = models.CharField(_('title'), max_length=50)
    amount = models.DecimalField(_('amount'), max_digits=10, decimal_places=2)
    slot_num = models.IntegerField(_('number of slots'))
    comment = models.CharField(_('comment'), max_length=200)
    event = models.ForeignKey(Event, related_name="items", verbose_name=('event'))

    def __str__(self):
        return self.title


class Slot(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='slots', verbose_name=_('item'))
    guest = models.ForeignKey(auth.models.User, related_name='slots', null=True,
                              blank=True, verbose_name=_('filled by'))
    comment = models.CharField(_('comment'), max_length=100, null=True, blank=True)
    index = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return "{} #{}".format(self.item.title, self.index)


class Guest(models.Model):
    class Status:
        NO_RESPONSE = 1
        ACCEPTED = 2
        DECLINED = 3
        MAYBE = 4

        choices = ((NO_RESPONSE, _('no response')), (ACCEPTED, _('accepted')), (DECLINED, _('declined')), (MAYBE, _('maybe'))
                   )
    name = models.CharField(_('name'), max_length=200)
    email = models.EmailField(_('email'))
    status = models.IntegerField(_('response'), choices=Status.choices, default=Status.NO_RESPONSE)
    invited_by = models.ForeignKey(auth.models.User, related_name='invitees', verbose_name=_('invited_by'))
    invited_at = models.DateTimeField(_('invited_at'))
    secret_code = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(auth.models.User, null=True, blank=True, related_name='invitations')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name=_('event'))

    def __str__(self):
        return "{}: {} {}".format(self.event.title, self.name, self.email)

    class Meta:
        unique_together = (('event', 'email'))


    # class EventGuests(models.Model):
    #     ''' many2many relationship events - guests
    #     '''
    #     guest = models.ForeignKey(auth.models.User, related_name='guest_events')
    #     event = models.ForeignKey(Event, related_name='event_guests')
    #     can_edit = models.BooleanField(default=False)
    #
    #     class Meta:
    #         unique_together = (('guest', 'event'))
    #
    #     def __str__(self):
    #         return self.guest.username

    # class Person(models.Model):
    #         first_name = models.CharField(max_length=30)
    #         last_name = models.CharField(max_length=30)
    #         birthday = models.DateTimeField()
    #
    #         def __str__(self):
    #                 return self.last_name + ",  " + self.first_name

    # class Ad(models.Model):
    #     posted_at = models.DateTimeField(auto_now_add=True)
    #
    #     title = models.CharField(max_length=200)
    #     description = models.TextField()
    #
    #     posted_by = models.CharField(max_length=200)
    #     contact_email = models.EmailField()
    #     contact_phone = models.CharField(max_length=30,  null=True, blank=True)
    #     price = models.PositiveIntegerField(null=True, blank=True)
    # price = models.DateTimeField()

    # o = Ad()
    # o.titl= "name"    ...

events/forms.py
from datetimewidget.widgets import DateTimeWidget
from django import forms
import events.models


class LoginForm(forms.Form):
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())



class GuestForm(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField()


class GuestReponseForm(forms.ModelForm):

    class Meta:
        model = events.models.Guest
        fields = ['status']

    status = forms.ChoiceField(label='Please Respond', widget=forms.RadioSelect, choices=events.models.Guest.Status.choices[1:])

class EventForm(forms.ModelForm):

    class Meta:
        model = events.models.Event
        fields = (
            'title',
            'start',
            'end',
            'description',
            'price',
            'status',
            'location',
        )
    start = forms.DateTimeField(label='starts at', widget=DateTimeWidget(bootstrap_version=3, attrs={'data-readonly': 'false'}))
    end = forms.DateTimeField(label='ends at', widget=DateTimeWidget(bootstrap_version=3, attrs={'data-readonly': 'false'}))

events/views.py
import datetime
from django.core.mail import send_mail
import geocoder
from django.contrib.auth import authenticate, login, logout
from django.core.mail import send_mail
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import redirect, get_object_or_404
from django.utils.encoding import escape_uri_path
from django.views.generic import View
from django.views.generic.edit import CreateView, FormView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from events.forms import GuestForm
from django.http import HttpResponseForbidden
import events.forms
import events.models
from django.contrib import messages
import random

# Create your views here.


class LoginView(FormView):
    form_class = events.forms.LoginForm
    template_name = "login.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('events:home')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

        if user is not None and user.is_active:
            login(self.request, user)
            if self.request.GET.get('from'):
                return redirect(
                    self.request.GET['from'])  # SECURITY: check path
            return redirect('events:home')

        form.add_error(None, "Invalid user name or password")
        return self.form_invalid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("login")


class LoggedInMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            url = reverse("login") + "?from=" + escape_uri_path(request.path)
            return redirect(url)
        return super().dispatch(request, *args, **kwargs)


class EventMixin:
    template_name = "events/event_form.html"
    # model = events.models.Event
    # fields = (
    #     'title',
    #     'start',
    #     'end',
    #     'description',
    #     'price',
    #     'status',
    #     'location',
    # )
    form_class = events.forms.EventForm
    success_url = reverse_lazy('events:home')

    def get_initial(self):
        return super().get_initial()

    def form_valid(self, form):
        # assert False, self.request.user.username

        form.instance.latitude = geocoder.google(form.instance.location).latlng[0]
        form.instance.longitude = geocoder.google(form.instance.location).latlng[1]

        form.instance.host = self.request.user
        return super().form_valid(form)


class CreateEventView(LoggedInMixin, EventMixin, CreateView):

    # template = "events/event_form.html"
    def title(self):
        return "Add New event"

    def form_valid(self, form):
        messages.success(self.request, 'Succefully created event: ' + form.instance.title)
        return super().form_valid(form)


class UpdateEventView(LoggedInMixin, EventMixin, UpdateView):
    # template = "events/event_form.html"
    model = events.models.Event

    def title(self):
        return self.object.title

    def form_valid(self, form):
        messages.success(self.request, 'Succefully updated event: ' + form.instance.title)
        return super().form_valid(form)


class DetailsEventView(DetailView):

    def title(self):
        return self.object.title

    model = events.models.Event
    success_url = reverse_lazy('events:update')

    def get_context_data(self, **kwargs):
        context = super(DetailsEventView, self).get_context_data(**kwargs)

        return context


class EventListView(LoggedInMixin, ListView):
    def title(self):
        return "Home"
    model = events.models.Event


class CreateGuestView(LoggedInMixin, FormView):
    page_title = "create guests"
    template_name = 'events/guest_form.html'
    form_class = GuestForm
    # model = models.Guest
    # fields = (
    #     'name',
    #     'email'
    # )

    success_url = reverse_lazy('events:home')


    def form_valid(self, form):

        subject = 'title' #form.cleaned_data['subject']
        message = 'description'
        sender = 'lital.jos@gmail.com'
        recipients = [form.cleaned_data['email']]

        send_mail(subject, message, sender, recipients)

        return super().form_valid(form)

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(CreateGuestView, self).get_context_data(**kwargs)
        return context



class GuestResponseView(LoggedInMixin, UpdateView):
    model = events.models.Guest
    def title(self):
        return "RSVP"

    slug_field = 'secret_code'
    form_class = events.forms.GuestReponseForm
    template_name = 'events/guest_response.html'

    # fields = ('status', )

    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        # d['guest'] = get_object_or_404(models.Guest.objects, secret_code= self.kwargs['slug'])
        # d['statuses'] = models.Guest.Status.choices
        return d

    def form_valid(self, form):
        # assert False, dir(form)
        # guest = get_object_or_404(models.Guest.objects, secret_code= self.kwargs['secret'])
        # guest.status = form.data['guest_response']
        # form.instance.date = datetime.date.today()
        o = form.save()
        # assert False, dir(self.request)
        send_mail(
            'Response to invitation {} received'.format(form.instance.event.title),
            '''
            Dear {user},

            Thank you for responding to the invitation to {event}.
            You can always edit your response here {rsvp_url} or view the event details here {event_url}.
            '''.format(user=form.instance.name, event=form.instance.event.title, event_url = self.request.build_absolute_uri(reverse("events:details", kwargs={'pk':form.instance.event_id})), rsvp_url = self.request.build_absolute_uri(self.request.get_full_path())),
            'from@example.com',
            [form.instance.email],
            fail_silently=False,
        )
        messages.success(self.request, 'Your response has been recorded')
        return redirect('events:details', pk=form.instance.event_id)

events/templates/events/event_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }} » <a href="{% url 'events:home' %}">Events</a> » {{ view.title }}
{% endblock %}
{% block content %}

<script>
    jQuery(document).ready(function($) {
    $(".btn").click(function() {
        window.document.location = $(this).attr('href');
    });
});
    jQuery(document).ready(function($) {
    $("#home").click(function() {
        window.document.location = $(this).attr('href');
    });
});

</script>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <p>{{ object.start }}       </p>
            <p>{{ object.end }}         </p>
            <p>{{ object.description }} </p>
            <p>{{ object.price }}       </p>
            <p>{{ object.get_status_display }}      </p>
            <p>{{ object.location }}    </p>
            <p>{{ object.latitude }}    </p>
            <p>{{ object.longitude }}   </p>
        </div>
        <div class="col-md-6">
            <table class="table table-responsive">
                <caption><strong>Guests</strong></caption>
                <tbody>
                    {% for guest in object.guest_set.all %}
                    <tr>
                        <td>{{ guest.name }}</td>
                        <td>{{ guest.get_status_display }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    <div>

<div class="clearfix"></div>
    {% buttons %}
    <button type="submit" class="btn btn-primary" href="{% url 'events:update' object.pk %}">
        update {% bootstrap_icon "pencil" %}
    </button>
    <button type="button" class="btn btn-primary" id="guest" href="{% url 'events:guest' %}">
        Add guests
    </button>
    <button type="button" class="btn btn-primary" id="home" href="{% url 'events:home' %}">
        Back to event list
    </button>
    {% endbuttons %}
{#</div>#}

    </div>

{% endblock %}

events/templates/events/event_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

<<<<<<< HEAD
=======
{% block breadcrumbs %}
    {{ block.super }} » <a href="{% url 'events:home' %}">Events</a> » {{ view.title }}
{% endblock %}
>>>>>>> 57389f0dd4d0a6f11b5ba6ce5af58a85d34f0701
{% block content %}

<script>jQuery(document).ready(function($) {
    $("#cancel").click(function() {
        window.document.location = $(this).attr('href');
    });
});
jQuery(document).ready(function($) {
    $("#guest").click(function() {
        window.document.location = $(this).attr('href');
    });
});
</script>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Save {% bootstrap_icon "save" %}
            </button>
            <button type="button" class="btn btn-primary" id="cancel" href="{% url 'events:home' %}">
                Cancel
            </button>
            <button type="submit" class="btn btn-primary" id="guest" href="{% url 'events:guest' %}">
                Add guest
            </button>
        {% endbuttons %}
    </form>


{% endblock %}

events/templates/events/event_list.html
{% extends "base.html" %}

{% block content %}

    <script>
    jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.document.location = $(this).find("a").attr('href');
    });
});
</script>
    <div class="pull-right">
        <a href="{% url 'events:create' %}">+ Create new event</a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Event</th>
            <th>Starts at</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}

            <tr class="clickable-row" >
                <td style="cursor: pointer"><a href="{% url 'events:details' object.pk %}"> {{ object.title }}</a></td>
                <td>{{ object.start }}</td>
                <td>{{ object.get_status_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

events/templates/events/guest_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }} » <a href="{% url 'events:home' %}">Events</a> » {{ view.title }}
{#    <a href="{% url 'events:details' object.event_id %}">{{  object.event.title }}</a> » {{ view.title }}#}
{% endblock %}

{% block content %}

<script>
    jQuery(document).ready(function($) {
    $(".btn").click(function() {
        window.document.location = $(this).attr('href');
    });
});
    jQuery(document).ready(function($) {
    $("#home").click(function() {
        window.document.location = $(this).attr('href');
    });
});
</script>

<form method="post" enctype="multipart/form-data">

    {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Invite {% bootstrap_icon "send" %}
            </button>
        {% endbuttons %}

</form>
    {% buttons %}
    <button type="button" class="btn btn-primary" id="home" href="{% url 'events:home' %}">
        Back to event list
    </button>
    {% endbuttons %}

{% endblock %}

events/templates/events/guest_response.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block breadcrumbs %}
    {{ block.super }} » <a href="{% url 'events:home' %}">Events</a> » <a href="{% url 'events:details' form.instance.event_id %}">{{  form.instance.event.title }}</a> » {{ view.title }}
{% endblock %}
{% block content %}

    <form method="post">

        {% csrf_token %}
        <div>
            <h2 class="text-center"><strong>{{ form.instance.invited_by|capfirst }}</strong> invited you to <strong>{{ form.instance.event.title }}</strong></h2>
            <p>{{ form.instance.event.description|linebreaks }}</p>
            <p><span class="label label-default">Event time:</span>  {{ form.instance.event.start }} - {{ form.instance.event.end }}</p>
            <p><span class="label label-default">Event location:</span>  {{ form.instance.event.location|capfirst }}</p>
        </div>

        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                Respond {% bootstrap_icon "send" %}
            </button>
        {% endbuttons %}

    </form>

{% endblock %}